slice_name: "EDI \xB7 Volume actual vs expected"
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 79__table
  viz_type: echarts_timeseries_line
  x_axis: shipment_date
  time_grain_sqla: P1D
  groupby: []
  metrics:
  - expressionType: SQL
    sqlExpression: SUM(actual_volume)
    label: actual
    hasCustomLabel: true
  row_limit: 10000
  time_range: No filter
  y_axis_format: SMART_NUMBER
query_context: '{"datasource": {"id": 79, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": "", "time_grain_sqla": "P1D"},
  "applied_time_extras": {}, "annotation_layers": [], "url_params": {}, "custom_params":
  {}, "custom_form_data": {}, "row_limit": 10000, "orderby": [[{"expressionType":
  "SQL", "sqlExpression": "SUM(actual_volume)", "label": "actual", "hasCustomLabel":
  true}, false]], "columns": [{"timeGrain": "P1D", "columnType": "BASE_AXIS", "sqlExpression":
  "shipment_date", "label": "shipment_date", "expressionType": "SQL"}], "metrics":
  [{"expressionType": "SQL", "sqlExpression": "SUM(actual_volume)", "label": "actual",
  "hasCustomLabel": true}], "series_columns": []}], "form_data": {"datasource": "79__table",
  "viz_type": "echarts_timeseries_line", "x_axis": "shipment_date", "time_grain_sqla":
  "P1D", "groupby": [], "metrics": [{"expressionType": "SQL", "sqlExpression": "SUM(actual_volume)",
  "label": "actual", "hasCustomLabel": true}], "row_limit": 10000, "time_range": "No
  filter", "y_axis_format": "SMART_NUMBER"}, "result_format": "json", "result_type":
  "full"}'
cache_timeout: null
uuid: 99016ebc-6869-40ae-884c-f8ffb4d150cf
version: 1.0.0
dataset_uuid: 3bf4a16e-92a7-40fb-a09d-d4a7862967f8
tags: []
