slice_name: "EDI \xB7 ACK SLA trend"
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 77__table
  viz_type: echarts_timeseries_line
  x_axis: metric_date
  time_grain_sqla: P1D
  groupby: []
  metrics:
  - expressionType: SQL
    sqlExpression: AVG(ack_sla_percent)
    label: ack
    hasCustomLabel: true
  row_limit: 10000
  time_range: No filter
  y_axis_format: .1f
query_context: '{"datasource": {"id": 77, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": "", "time_grain_sqla": "P1D"},
  "applied_time_extras": {}, "annotation_layers": [], "url_params": {}, "custom_params":
  {}, "custom_form_data": {}, "row_limit": 10000, "orderby": [[{"expressionType":
  "SQL", "sqlExpression": "AVG(ack_sla_percent)", "label": "ack", "hasCustomLabel":
  true}, false]], "columns": [{"timeGrain": "P1D", "columnType": "BASE_AXIS", "sqlExpression":
  "metric_date", "label": "metric_date", "expressionType": "SQL"}], "metrics": [{"expressionType":
  "SQL", "sqlExpression": "AVG(ack_sla_percent)", "label": "ack", "hasCustomLabel":
  true}], "series_columns": []}], "form_data": {"datasource": "77__table", "viz_type":
  "echarts_timeseries_line", "x_axis": "metric_date", "time_grain_sqla": "P1D", "groupby":
  [], "metrics": [{"expressionType": "SQL", "sqlExpression": "AVG(ack_sla_percent)",
  "label": "ack", "hasCustomLabel": true}], "row_limit": 10000, "time_range": "No
  filter", "y_axis_format": ".1f"}, "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: 7cabef44-cc02-4aef-b265-716126b05f61
version: 1.0.0
dataset_uuid: ba6ac939-5433-4fb2-a119-247694c8b271
tags: []
