slice_name: "EDI \xB7 Critical (count)"
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 71__table
  viz_type: big_number_total
  metric:
    expressionType: SQL
    sqlExpression: COUNT(*) FILTER (WHERE severity='Critical')
    label: n
    hasCustomLabel: true
  subheader: critical severity
  time_range: No filter
  y_axis_format: SMART_NUMBER
query_context: '{"datasource": {"id": 71, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": ""}, "applied_time_extras": {},
  "annotation_layers": [], "url_params": {}, "custom_params": {}, "custom_form_data":
  {}, "row_limit": 1, "orderby": [], "columns": [], "metrics": [{"expressionType":
  "SQL", "sqlExpression": "COUNT(*) FILTER (WHERE severity=''Critical'')", "label":
  "n", "hasCustomLabel": true}]}], "form_data": {"datasource": "71__table", "viz_type":
  "big_number_total", "metric": {"expressionType": "SQL", "sqlExpression": "COUNT(*)
  FILTER (WHERE severity=''Critical'')", "label": "n", "hasCustomLabel": true}, "subheader":
  "critical severity", "time_range": "No filter", "y_axis_format": "SMART_NUMBER"},
  "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: 70b50e3c-3a84-4200-8301-f33d4b791533
version: 1.0.0
dataset_uuid: 1d60b982-bdac-4ebb-bff7-58c0b65fff39
tags: []
