slice_name: "EDI \xB7 Anomaly rate by partner"
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 73__table
  viz_type: echarts_timeseries_bar
  x_axis: partner_name
  groupby: []
  metrics:
  - expressionType: SQL
    sqlExpression: MAX(anomaly_rate_pct)
    label: rate
    hasCustomLabel: true
  row_limit: 100
  time_range: No filter
  x_axis_sort_asc: false
  x_axis_sort_series: name
  order_desc: true
query_context: '{"datasource": {"id": 73, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": ""}, "applied_time_extras": {},
  "annotation_layers": [], "url_params": {}, "custom_params": {}, "custom_form_data":
  {}, "row_limit": 100, "orderby": [[{"expressionType": "SQL", "sqlExpression": "MAX(anomaly_rate_pct)",
  "label": "rate", "hasCustomLabel": true}, false]], "columns": ["partner_name"],
  "metrics": [{"expressionType": "SQL", "sqlExpression": "MAX(anomaly_rate_pct)",
  "label": "rate", "hasCustomLabel": true}], "series_columns": []}], "form_data":
  {"datasource": "73__table", "viz_type": "echarts_timeseries_bar", "x_axis": "partner_name",
  "groupby": [], "metrics": [{"expressionType": "SQL", "sqlExpression": "MAX(anomaly_rate_pct)",
  "label": "rate", "hasCustomLabel": true}], "row_limit": 100, "time_range": "No filter",
  "x_axis_sort_asc": false, "x_axis_sort_series": "name", "order_desc": true}, "result_format":
  "json", "result_type": "full"}'
cache_timeout: null
uuid: 6fcf46f2-b15f-4d40-a072-bed6b94bc212
version: 1.0.0
dataset_uuid: 9104475b-b4c5-4b95-9583-f8e56cffc3e5
tags: []
