slice_name: "EDI \xB7 Anomaly trend (daily)"
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 68__table
  viz_type: echarts_timeseries_bar
  x_axis: metric_date
  time_grain_sqla: P1D
  groupby: []
  metrics:
  - expressionType: SQL
    sqlExpression: SUM(total_anomalies)
    label: anomalies
    hasCustomLabel: true
  row_limit: 10000
  time_range: No filter
  y_axis_format: SMART_NUMBER
query_context: '{"datasource": {"id": 68, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": "", "time_grain_sqla": "P1D"},
  "applied_time_extras": {}, "annotation_layers": [], "url_params": {}, "custom_params":
  {}, "custom_form_data": {}, "row_limit": 10000, "orderby": [[{"expressionType":
  "SQL", "sqlExpression": "SUM(total_anomalies)", "label": "anomalies", "hasCustomLabel":
  true}, false]], "columns": [{"timeGrain": "P1D", "columnType": "BASE_AXIS", "sqlExpression":
  "metric_date", "label": "metric_date", "expressionType": "SQL"}], "metrics": [{"expressionType":
  "SQL", "sqlExpression": "SUM(total_anomalies)", "label": "anomalies", "hasCustomLabel":
  true}], "series_columns": []}], "form_data": {"datasource": "68__table", "viz_type":
  "echarts_timeseries_bar", "x_axis": "metric_date", "time_grain_sqla": "P1D", "groupby":
  [], "metrics": [{"expressionType": "SQL", "sqlExpression": "SUM(total_anomalies)",
  "label": "anomalies", "hasCustomLabel": true}], "row_limit": 10000, "time_range":
  "No filter", "y_axis_format": "SMART_NUMBER"}, "result_format": "json", "result_type":
  "full"}'
cache_timeout: null
uuid: 22baf5b6-3797-4aac-a35e-e16edd6af722
version: 1.0.0
dataset_uuid: 2371f614-c4c8-4e70-9467-261e505e3624
tags: []
