slice_name: "EDI \xB7 Status distribution"
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 70__table
  viz_type: echarts_timeseries_bar
  x_axis: current_status
  groupby: []
  metrics:
  - expressionType: SQL
    sqlExpression: SUM(shipment_count)
    label: ships
    hasCustomLabel: true
  row_limit: 40
  time_range: No filter
  x_axis_sort_asc: false
  x_axis_sort_series: name
  order_desc: true
query_context: '{"datasource": {"id": 70, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": ""}, "applied_time_extras": {},
  "annotation_layers": [], "url_params": {}, "custom_params": {}, "custom_form_data":
  {}, "row_limit": 40, "orderby": [[{"expressionType": "SQL", "sqlExpression": "SUM(shipment_count)",
  "label": "ships", "hasCustomLabel": true}, false]], "columns": ["current_status"],
  "metrics": [{"expressionType": "SQL", "sqlExpression": "SUM(shipment_count)", "label":
  "ships", "hasCustomLabel": true}], "series_columns": []}], "form_data": {"datasource":
  "70__table", "viz_type": "echarts_timeseries_bar", "x_axis": "current_status", "groupby":
  [], "metrics": [{"expressionType": "SQL", "sqlExpression": "SUM(shipment_count)",
  "label": "ships", "hasCustomLabel": true}], "row_limit": 40, "time_range": "No filter",
  "x_axis_sort_asc": false, "x_axis_sort_series": "name", "order_desc": true}, "result_format":
  "json", "result_type": "full"}'
cache_timeout: null
uuid: ff010808-86d8-4140-89cb-5ffbb0b1c352
version: 1.0.0
dataset_uuid: ece3bf05-9628-41a2-9cb8-480c0af69c89
tags: []
