slice_name: "EDI \xB7 Avg partner health"
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 66__table
  viz_type: big_number_total
  metric:
    expressionType: SQL
    sqlExpression: MAX(avg_partner_health_score)
    label: health
    hasCustomLabel: true
  subheader: avg health score
  time_range: No filter
  y_axis_format: .0f
query_context: '{"datasource": {"id": 66, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": ""}, "applied_time_extras": {},
  "annotation_layers": [], "url_params": {}, "custom_params": {}, "custom_form_data":
  {}, "row_limit": 1, "orderby": [], "columns": [], "metrics": [{"expressionType":
  "SQL", "sqlExpression": "MAX(avg_partner_health_score)", "label": "health", "hasCustomLabel":
  true}]}], "form_data": {"datasource": "66__table", "viz_type": "big_number_total",
  "metric": {"expressionType": "SQL", "sqlExpression": "MAX(avg_partner_health_score)",
  "label": "health", "hasCustomLabel": true}, "subheader": "avg health score", "time_range":
  "No filter", "y_axis_format": ".0f"}, "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: c63e2be5-9fa5-4cc2-9bf1-92e32153043e
version: 1.0.0
dataset_uuid: 15601a36-717e-4ebc-85cf-61c145ccdea1
tags: []
