slice_name: Processed
description: null
certified_by: null
certification_details: null
viz_type: big_number
params:
  datasource: 74__table
  viz_type: big_number
  slice_id: 210
  x_axis: transaction_date
  time_grain_sqla: P1D
  aggregation: sum
  metric:
    aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Transactions
    optionName: metric_ak64gxboc9j_xv81nswqk4
    sqlExpression: case when sum(transaction_count) is null then 0 else  sum(transaction_count)  end
  adhoc_filters:
  - clause: WHERE
    comparator:
    - processed
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_v2jm8fa6hn_mu3krr6psna
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: processing_status
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_g71xneimx9b_k1q9xdk2buf
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: transaction_date
  compare_lag: 7
  show_trend_line: false
  start_y_axis_at_zero: true
  color_picker:
    a: 1
    b: 135
    g: 122
    r: 0
  header_font_size: 0.4
  subheader_font_size: 0.15
  subtitle_font_size: 0.15
  metric_name_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  rolling_type: None
  extra_form_data: {}
  dashboards:
  - 29
query_context: '{"datasource":{"id":74,"type":"table"},"force":false,"queries":[{"filters":[{"col":"processing_status","op":"IN","val":["processed"]},{"col":"transaction_date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"transaction_date","label":"transaction_date","expressionType":"SQL","isColumnReference":true}],"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Transactions","optionName":"metric_ak64gxboc9j_xv81nswqk4","sqlExpression":"case
  when sum(transaction_count) is null then 0 else  sum(transaction_count)  end"}],"annotation_layers":[],"series_limit":0,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[{"operation":"pivot","options":{"index":["transaction_date"],"columns":[],"aggregates":{"Transactions":{"operator":"mean"}},"drop_missing_columns":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"74__table","viz_type":"big_number","slice_id":210,"x_axis":"transaction_date","time_grain_sqla":"P1D","aggregation":"sum","metric":{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Transactions","optionName":"metric_ak64gxboc9j_xv81nswqk4","sqlExpression":"case
  when sum(transaction_count) is null then 0 else  sum(transaction_count)  end"},"adhoc_filters":[{"clause":"WHERE","comparator":["processed"],"datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_v2jm8fa6hn_mu3krr6psna","isExtra":false,"isNew":false,"operator":"IN","operatorId":"IN","sqlExpression":null,"subject":"processing_status"},{"clause":"WHERE","comparator":"No
  filter","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_g71xneimx9b_k1q9xdk2buf","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","sqlExpression":null,"subject":"transaction_date"}],"compare_lag":7,"show_trend_line":false,"start_y_axis_at_zero":true,"color_picker":{"a":1,"b":135,"g":122,"r":0},"header_font_size":0.4,"subheader_font_size":0.15,"subtitle_font_size":0.15,"metric_name_font_size":0.15,"y_axis_format":"SMART_NUMBER","time_format":"smart_date","rolling_type":"None","extra_form_data":{},"dashboards":[29],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: d096790e-dc6b-49b8-881a-177ea6534f0f
version: 1.0.0
dataset_uuid: d0ccbe04-275a-4bde-b713-5a593318e910
