slice_name: Technical SLA Trend
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 106__table
  viz_type: echarts_timeseries_line
  slice_id: 250
  x_axis: metric_date
  time_grain_sqla: P1D
  x_axis_sort_asc: true
  metrics:
  - aggregate: AVG
    column:
      advanced_data_type: null
      changed_on: '2026-06-23T04:28:52.958369'
      column_name: sla_percent
      created_on: '2026-06-23T04:28:52.958368'
      description: null
      expression: null
      extra: null
      filterable: true
      groupby: true
      id: 5995
      is_active: true
      is_dttm: false
      python_date_format: null
      type: NUMERIC
      type_generic: 0
      uuid: 0ee30b7c-6c9c-4a63-b55b-3e1f9e8709ca
      verbose_name: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: AVG(sla_percent)
    optionName: metric_lk66wd7cn39_8sij7zfdutt
    sqlExpression: null
  groupby:
  - sla_type
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: metric_date
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  rolling_type: null
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title_margin: 30
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  time_shift_color: true
  only_total: true
  opacity: 0.2
  markerSize: 6
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  xAxisLabelInterval: auto
  rich_tooltip: true
  showTooltipTotal: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":106,"type":"table"},"force":false,"queries":[{"filters":[{"col":"metric_date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"metric_date","label":"metric_date","expressionType":"SQL","isColumnReference":true},"sla_type"],"metrics":[{"aggregate":"AVG","column":{"advanced_data_type":null,"changed_on":"2026-06-23T04:28:52.958369","column_name":"sla_percent","created_on":"2026-06-23T04:28:52.958368","description":null,"expression":null,"extra":null,"filterable":true,"groupby":true,"id":5995,"is_active":true,"is_dttm":false,"python_date_format":null,"type":"NUMERIC","type_generic":0,"uuid":"0ee30b7c-6c9c-4a63-b55b-3e1f9e8709ca","verbose_name":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"AVG(sla_percent)","optionName":"metric_lk66wd7cn39_8sij7zfdutt","sqlExpression":null}],"orderby":[[{"aggregate":"AVG","column":{"advanced_data_type":null,"changed_on":"2026-06-23T04:28:52.958369","column_name":"sla_percent","created_on":"2026-06-23T04:28:52.958368","description":null,"expression":null,"extra":null,"filterable":true,"groupby":true,"id":5995,"is_active":true,"is_dttm":false,"python_date_format":null,"type":"NUMERIC","type_generic":0,"uuid":"0ee30b7c-6c9c-4a63-b55b-3e1f9e8709ca","verbose_name":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"AVG(sla_percent)","optionName":"metric_lk66wd7cn39_8sij7zfdutt","sqlExpression":null},false]],"annotation_layers":[],"row_limit":10000,"series_columns":["sla_type"],"series_limit":0,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["metric_date"],"columns":["sla_type"],"aggregates":{"AVG(sla_percent)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"rename","options":{"columns":{"AVG(sla_percent)":null},"level":0,"inplace":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"106__table","viz_type":"echarts_timeseries_line","slice_id":250,"x_axis":"metric_date","time_grain_sqla":"P1D","x_axis_sort_asc":true,"metrics":[{"aggregate":"AVG","column":{"advanced_data_type":null,"changed_on":"2026-06-23T04:28:52.958369","column_name":"sla_percent","created_on":"2026-06-23T04:28:52.958368","description":null,"expression":null,"extra":null,"filterable":true,"groupby":true,"id":5995,"is_active":true,"is_dttm":false,"python_date_format":null,"type":"NUMERIC","type_generic":0,"uuid":"0ee30b7c-6c9c-4a63-b55b-3e1f9e8709ca","verbose_name":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"AVG(sla_percent)","optionName":"metric_lk66wd7cn39_8sij7zfdutt","sqlExpression":null}],"groupby":["sla_type"],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"metric_date"}],"order_desc":true,"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"rolling_type":null,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"x_axis_title_margin":15,"y_axis_title_margin":30,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","time_shift_color":true,"only_total":true,"opacity":0.2,"markerSize":6,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","xAxisLabelInterval":"auto","rich_tooltip":true,"showTooltipTotal":true,"tooltipTimeFormat":"smart_date","y_axis_format":"SMART_NUMBER","truncateXAxis":true,"y_axis_bounds":[null,null],"extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 8eaa0cf1-143e-47d4-9230-5df270d06bde
version: 1.0.0
dataset_uuid: 95c39611-eb93-4fdf-9208-055bb5552f12
