slice_name: 'LOB: Traffic trend'
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 22__table
  viz_type: echarts_timeseries_bar
  x_axis: bucket
  time_grain_sqla: P1D
  groupby:
  - doc_type
  metrics:
  - expressionType: SQL
    sqlExpression: SUM(txn_count)
    label: txns
    hasCustomLabel: true
  row_limit: 10000
  time_range: No filter
query_context: '{"datasource": {"id": 22, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": "", "time_grain_sqla": "P1D"},
  "applied_time_extras": {}, "annotation_layers": [], "url_params": {}, "custom_params":
  {}, "custom_form_data": {}, "row_limit": 10000, "orderby": [[{"expressionType":
  "SQL", "sqlExpression": "SUM(txn_count)", "label": "txns", "hasCustomLabel": true},
  false]], "columns": [{"timeGrain": "P1D", "columnType": "BASE_AXIS", "sqlExpression":
  "bucket", "label": "bucket", "expressionType": "SQL"}, "doc_type"], "metrics": [{"expressionType":
  "SQL", "sqlExpression": "SUM(txn_count)", "label": "txns", "hasCustomLabel": true}],
  "series_columns": ["doc_type"]}], "form_data": {"datasource": "22__table", "viz_type":
  "echarts_timeseries_bar", "x_axis": "bucket", "time_grain_sqla": "P1D", "groupby":
  ["doc_type"], "metrics": [{"expressionType": "SQL", "sqlExpression": "SUM(txn_count)",
  "label": "txns", "hasCustomLabel": true}], "row_limit": 10000, "time_range": "No
  filter"}, "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: 7d8f9723-29f0-405d-8f59-12bc69a1017e
version: 1.0.0
dataset_uuid: 508a1b2a-c7f0-4040-974c-7373d1d85a80
tags: []
