slice_name: 'LOB: Count by message type'
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 22__table
  viz_type: echarts_timeseries_bar
  x_axis: doc_type
  groupby:
  - status
  metrics:
  - expressionType: SQL
    sqlExpression: SUM(txn_count)
    label: txns
    hasCustomLabel: true
  row_limit: 30
  time_range: No filter
  x_axis_sort_asc: false
  x_axis_sort_series: name
  order_desc: true
query_context: '{"datasource": {"id": 22, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": ""}, "applied_time_extras": {},
  "annotation_layers": [], "url_params": {}, "custom_params": {}, "custom_form_data":
  {}, "row_limit": 30, "orderby": [[{"expressionType": "SQL", "sqlExpression": "SUM(txn_count)",
  "label": "txns", "hasCustomLabel": true}, false]], "columns": ["doc_type", "status"],
  "metrics": [{"expressionType": "SQL", "sqlExpression": "SUM(txn_count)", "label":
  "txns", "hasCustomLabel": true}], "series_columns": ["status"]}], "form_data": {"datasource":
  "22__table", "viz_type": "echarts_timeseries_bar", "x_axis": "doc_type", "groupby":
  ["status"], "metrics": [{"expressionType": "SQL", "sqlExpression": "SUM(txn_count)",
  "label": "txns", "hasCustomLabel": true}], "row_limit": 30, "time_range": "No filter",
  "x_axis_sort_asc": false, "x_axis_sort_series": "name", "order_desc": true}, "result_format":
  "json", "result_type": "full"}'
cache_timeout: null
uuid: c5b87945-e0ba-42c2-a9c7-caff7682c5ff
version: 1.0.0
dataset_uuid: 508a1b2a-c7f0-4040-974c-7373d1d85a80
tags: []
