slice_name: Overall compliance %
description: null
certified_by: null
certification_details: null
viz_type: gauge_chart
params:
  datasource: 45__table
  viz_type: gauge_chart
  metric:
    expressionType: SQL
    sqlExpression: 100.0*count(*) FILTER (WHERE sla_state='met')/NULLIF(count(*) FILTER
      (WHERE sla_state IN ('met','missed')),0)
    label: compliance
    hasCustomLabel: true
  row_limit: 1
  time_range: No filter
  min_val: 0
  max_val: 100
query_context: '{"datasource": {"id": 45, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": ""}, "applied_time_extras": {},
  "annotation_layers": [], "url_params": {}, "custom_params": {}, "custom_form_data":
  {}, "row_limit": 1, "orderby": [], "columns": [], "metrics": [{"expressionType":
  "SQL", "sqlExpression": "100.0*count(*) FILTER (WHERE sla_state=''met'')/NULLIF(count(*)
  FILTER (WHERE sla_state IN (''met'',''missed'')),0)", "label": "compliance", "hasCustomLabel":
  true}]}], "form_data": {"datasource": "45__table", "viz_type": "gauge_chart", "metric":
  {"expressionType": "SQL", "sqlExpression": "100.0*count(*) FILTER (WHERE sla_state=''met'')/NULLIF(count(*)
  FILTER (WHERE sla_state IN (''met'',''missed'')),0)", "label": "compliance", "hasCustomLabel":
  true}, "row_limit": 1, "time_range": "No filter", "min_val": 0, "max_val": 100},
  "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: 2097d765-810b-4da7-8d71-a59c513056e6
version: 1.0.0
dataset_uuid: f6f3d650-f430-4d5c-8642-59a11d7f1c70
tags: []
