slice_name: Rejected (period)
description: null
certified_by: null
certification_details: null
viz_type: big_number
params:
  datasource: 22__table
  viz_type: big_number
  metric:
    expressionType: SQL
    sqlExpression: SUM(rejected_count)
    label: rejected
    hasCustomLabel: true
  subheader: "rejected \u2014 its own state"
  time_range: No filter
  granularity_sqla: bucket
  time_grain_sqla: P1D
  compare_lag: ''
  y_axis_format: SMART_NUMBER
query_context: '{"datasource": {"id": 22, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": "", "time_grain_sqla": "P1D"},
  "applied_time_extras": {}, "annotation_layers": [], "url_params": {}, "custom_params":
  {}, "custom_form_data": {}, "row_limit": 10000, "orderby": [], "columns": [], "metrics":
  [{"expressionType": "SQL", "sqlExpression": "SUM(rejected_count)", "label": "rejected",
  "hasCustomLabel": true}], "is_timeseries": true, "granularity": "bucket"}], "form_data":
  {"datasource": "22__table", "viz_type": "big_number", "metric": {"expressionType":
  "SQL", "sqlExpression": "SUM(rejected_count)", "label": "rejected", "hasCustomLabel":
  true}, "subheader": "rejected \u2014 its own state", "time_range": "No filter",
  "granularity_sqla": "bucket", "time_grain_sqla": "P1D", "compare_lag": "", "y_axis_format":
  "SMART_NUMBER"}, "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: 4241c303-39b1-4f09-a668-68e587b34d78
version: 1.0.0
dataset_uuid: 508a1b2a-c7f0-4040-974c-7373d1d85a80
tags: []
