slice_name: Volume by protocol
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 44__table
  viz_type: echarts_timeseries_bar
  x_axis: protocol
  groupby: []
  metrics:
  - expressionType: SQL
    sqlExpression: SUM(txns)
    label: txns
    hasCustomLabel: true
  row_limit: 100
  time_range: No filter
  x_axis_sort_asc: false
  x_axis_sort_series: name
  order_desc: true
query_context: '{"datasource": {"id": 44, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": ""}, "applied_time_extras": {},
  "annotation_layers": [], "url_params": {}, "custom_params": {}, "custom_form_data":
  {}, "row_limit": 100, "orderby": [[{"expressionType": "SQL", "sqlExpression": "SUM(txns)",
  "label": "txns", "hasCustomLabel": true}, false]], "columns": ["protocol"], "metrics":
  [{"expressionType": "SQL", "sqlExpression": "SUM(txns)", "label": "txns", "hasCustomLabel":
  true}], "series_columns": []}], "form_data": {"datasource": "44__table", "viz_type":
  "echarts_timeseries_bar", "x_axis": "protocol", "groupby": [], "metrics": [{"expressionType":
  "SQL", "sqlExpression": "SUM(txns)", "label": "txns", "hasCustomLabel": true}],
  "row_limit": 100, "time_range": "No filter", "x_axis_sort_asc": false, "x_axis_sort_series":
  "name", "order_desc": true}, "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: c753cfa1-5a41-4d14-8675-10fb31dc9bff
version: 1.0.0
dataset_uuid: 8208df11-789e-4b9a-93ac-759fdbd57ac0
tags: []
