slice_name: Business impact $
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 71__table
  viz_type: big_number_total
  metric:
    expressionType: SQL
    sqlExpression: SUM(business_impact_amount)
    label: impact
    hasCustomLabel: true
  subheader: total impact
  time_range: No filter
  y_axis_format: $,.0f
query_context: '{"datasource": {"id": 71, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": ""}, "applied_time_extras": {},
  "annotation_layers": [], "url_params": {}, "custom_params": {}, "custom_form_data":
  {}, "row_limit": 1, "orderby": [], "columns": [], "metrics": [{"expressionType":
  "SQL", "sqlExpression": "SUM(business_impact_amount)", "label": "impact", "hasCustomLabel":
  true}]}], "form_data": {"datasource": "71__table", "viz_type": "big_number_total",
  "metric": {"expressionType": "SQL", "sqlExpression": "SUM(business_impact_amount)",
  "label": "impact", "hasCustomLabel": true}, "subheader": "total impact", "time_range":
  "No filter", "y_axis_format": "$,.0f"}, "result_format": "json", "result_type":
  "full"}'
cache_timeout: null
uuid: 0c8d4447-cdae-460c-a8f0-efa7e0df417a
version: 1.0.0
dataset_uuid: 1d60b982-bdac-4ebb-bff7-58c0b65fff39
tags: []
