slice_name: Document types
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 51__table
  viz_type: big_number_total
  metric:
    expressionType: SQL
    sqlExpression: COUNT(*)
    label: types
    hasCustomLabel: true
  subheader: distinct doc types
  time_range: No filter
  y_axis_format: SMART_NUMBER
query_context: '{"datasource": {"id": 51, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": ""}, "applied_time_extras": {},
  "annotation_layers": [], "url_params": {}, "custom_params": {}, "custom_form_data":
  {}, "row_limit": 1, "orderby": [], "columns": [], "metrics": [{"expressionType":
  "SQL", "sqlExpression": "COUNT(*)", "label": "types", "hasCustomLabel": true}]}],
  "form_data": {"datasource": "51__table", "viz_type": "big_number_total", "metric":
  {"expressionType": "SQL", "sqlExpression": "COUNT(*)", "label": "types", "hasCustomLabel":
  true}, "subheader": "distinct doc types", "time_range": "No filter", "y_axis_format":
  "SMART_NUMBER"}, "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: cf3b882f-0598-43fc-bac2-70fa2214d5d6
version: 1.0.0
dataset_uuid: eff3e74b-1c05-48f1-867a-9591c25a5243
tags: []
