slice_name: "EDI \xB7 EDI funnel"
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 74__table
  viz_type: echarts_timeseries_bar
  x_axis: funnel_stage
  groupby: []
  metrics:
  - expressionType: SQL
    sqlExpression: SUM(transaction_count)
    label: txns
    hasCustomLabel: true
  row_limit: 20
  time_range: No filter
  x_axis_sort_asc: false
  x_axis_sort_series: name
  order_desc: true
query_context: '{"datasource": {"id": 74, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": ""}, "applied_time_extras": {},
  "annotation_layers": [], "url_params": {}, "custom_params": {}, "custom_form_data":
  {}, "row_limit": 20, "orderby": [[{"expressionType": "SQL", "sqlExpression": "SUM(transaction_count)",
  "label": "txns", "hasCustomLabel": true}, false]], "columns": ["funnel_stage"],
  "metrics": [{"expressionType": "SQL", "sqlExpression": "SUM(transaction_count)",
  "label": "txns", "hasCustomLabel": true}], "series_columns": []}], "form_data":
  {"datasource": "74__table", "viz_type": "echarts_timeseries_bar", "x_axis": "funnel_stage",
  "groupby": [], "metrics": [{"expressionType": "SQL", "sqlExpression": "SUM(transaction_count)",
  "label": "txns", "hasCustomLabel": true}], "row_limit": 20, "time_range": "No filter",
  "x_axis_sort_asc": false, "x_axis_sort_series": "name", "order_desc": true}, "result_format":
  "json", "result_type": "full"}'
cache_timeout: null
uuid: 0208298b-afe6-4f9f-9b83-8ea32e50bbba
version: 1.0.0
dataset_uuid: 56498284-2715-4f34-b1f2-2b45da61f734
tags: []
