slice_name: 'LOB: Outgoing data'
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 62__table
  viz_type: table
  query_mode: raw
  all_columns:
  - event_time
  - business_ref
  - doc_type
  - status
  - payload
  order_by_cols:
  - '["event_time", false]'
  row_limit: 50
  server_page_length: 25
  time_range: No filter
query_context: '{"datasource": {"id": 62, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": ""}, "applied_time_extras": {},
  "annotation_layers": [], "url_params": {}, "custom_params": {}, "custom_form_data":
  {}, "row_limit": 50, "orderby": [["event_time", false]], "columns": ["event_time",
  "business_ref", "doc_type", "status", "payload"], "metrics": []}], "form_data":
  {"datasource": "62__table", "viz_type": "table", "query_mode": "raw", "all_columns":
  ["event_time", "business_ref", "doc_type", "status", "payload"], "order_by_cols":
  ["[\"event_time\", false]"], "row_limit": 50, "server_page_length": 25, "time_range":
  "No filter"}, "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: 592adacf-0de7-46f4-9951-0d22973f3d8b
version: 1.0.0
dataset_uuid: 14fe7107-5f7d-4b37-a5f2-c8c9cf1ec89e
tags: []
