slice_name: 'LOB: Exception queue'
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 64__table
  viz_type: table
  query_mode: raw
  all_columns:
  - event_time
  - business_ref
  - partner
  - doc_type
  - stage
  - status
  - reason_category
  - error_code
  - replay_count
  - age_min
  - comments
  order_by_cols:
  - '["event_time", false]'
  row_limit: 200
  server_page_length: 25
  time_range: No filter
  column_config:
    age_min:
      showCellBars: true
    replay_count:
      showCellBars: true
query_context: '{"datasource": {"id": 64, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": ""}, "applied_time_extras": {},
  "annotation_layers": [], "url_params": {}, "custom_params": {}, "custom_form_data":
  {}, "row_limit": 200, "orderby": [["event_time", false]], "columns": ["event_time",
  "business_ref", "partner", "doc_type", "stage", "status", "reason_category", "error_code",
  "replay_count", "age_min", "comments"], "metrics": []}], "form_data": {"datasource":
  "64__table", "viz_type": "table", "query_mode": "raw", "all_columns": ["event_time",
  "business_ref", "partner", "doc_type", "stage", "status", "reason_category", "error_code",
  "replay_count", "age_min", "comments"], "order_by_cols": ["[\"event_time\", false]"],
  "row_limit": 200, "server_page_length": 25, "time_range": "No filter", "column_config":
  {"age_min": {"showCellBars": true}, "replay_count": {"showCellBars": true}}}, "result_format":
  "json", "result_type": "full"}'
cache_timeout: null
uuid: 60666e70-a9cc-42a7-b861-79ca54ce2e20
version: 1.0.0
dataset_uuid: 2e5442f8-0c5b-4262-8b9f-2dd4a2469110
tags: []
