slice_name: Message SLA % by type
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 76__table
  viz_type: echarts_timeseries_bar
  x_axis: sla_type
  groupby: []
  metrics:
  - expressionType: SQL
    sqlExpression: AVG(sla_percent)
    label: sla
    hasCustomLabel: true
  row_limit: 100
  time_range: No filter
  x_axis_sort_asc: false
  x_axis_sort_series: name
  order_desc: true
query_context: '{"datasource": {"id": 76, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": ""}, "applied_time_extras": {},
  "annotation_layers": [], "url_params": {}, "custom_params": {}, "custom_form_data":
  {}, "row_limit": 100, "orderby": [[{"expressionType": "SQL", "sqlExpression": "AVG(sla_percent)",
  "label": "sla", "hasCustomLabel": true}, false]], "columns": ["sla_type"], "metrics":
  [{"expressionType": "SQL", "sqlExpression": "AVG(sla_percent)", "label": "sla",
  "hasCustomLabel": true}], "series_columns": []}], "form_data": {"datasource": "76__table",
  "viz_type": "echarts_timeseries_bar", "x_axis": "sla_type", "groupby": [], "metrics":
  [{"expressionType": "SQL", "sqlExpression": "AVG(sla_percent)", "label": "sla",
  "hasCustomLabel": true}], "row_limit": 100, "time_range": "No filter", "x_axis_sort_asc":
  false, "x_axis_sort_series": "name", "order_desc": true}, "result_format": "json",
  "result_type": "full"}'
cache_timeout: null
uuid: 92179e9e-48bb-4818-89cc-53213b7e7f96
version: 1.0.0
dataset_uuid: 91bfc60b-536d-4ad5-8c21-78e0386db5f9
tags: []
