slice_name: Re-failed replays
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 48__table
  viz_type: table
  query_mode: raw
  all_columns:
  - business_ref
  - partner
  - doc_type
  - replay_count
  - current_status
  order_by_cols: []
  row_limit: 100
  server_page_length: 25
  time_range: No filter
query_context: '{"datasource": {"id": 48, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": ""}, "applied_time_extras": {},
  "annotation_layers": [], "url_params": {}, "custom_params": {}, "custom_form_data":
  {}, "row_limit": 100, "orderby": [], "columns": ["business_ref", "partner", "doc_type",
  "replay_count", "current_status"], "metrics": []}], "form_data": {"datasource":
  "48__table", "viz_type": "table", "query_mode": "raw", "all_columns": ["business_ref",
  "partner", "doc_type", "replay_count", "current_status"], "order_by_cols": [], "row_limit":
  100, "server_page_length": 25, "time_range": "No filter"}, "result_format": "json",
  "result_type": "full"}'
cache_timeout: null
uuid: 00e8de84-7ce1-4722-bc30-8d44d2828063
version: 1.0.0
dataset_uuid: 589e80f0-3c18-45b3-9828-6da29cdb2146
tags: []
