slice_name: Top partners (filter by type)
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 54__table
  viz_type: echarts_timeseries_bar
  x_axis: partner
  groupby: []
  metrics:
  - expressionType: SQL
    sqlExpression: SUM(txns)
    label: txns
    hasCustomLabel: true
  row_limit: 20
  time_range: No filter
  x_axis_sort_asc: false
  x_axis_sort_series: name
  order_desc: true
query_context: '{"datasource": {"id": 54, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": ""}, "applied_time_extras": {},
  "annotation_layers": [], "url_params": {}, "custom_params": {}, "custom_form_data":
  {}, "row_limit": 20, "orderby": [[{"expressionType": "SQL", "sqlExpression": "SUM(txns)",
  "label": "txns", "hasCustomLabel": true}, false]], "columns": ["partner"], "metrics":
  [{"expressionType": "SQL", "sqlExpression": "SUM(txns)", "label": "txns", "hasCustomLabel":
  true}], "series_columns": []}], "form_data": {"datasource": "54__table", "viz_type":
  "echarts_timeseries_bar", "x_axis": "partner", "groupby": [], "metrics": [{"expressionType":
  "SQL", "sqlExpression": "SUM(txns)", "label": "txns", "hasCustomLabel": true}],
  "row_limit": 20, "time_range": "No filter", "x_axis_sort_asc": false, "x_axis_sort_series":
  "name", "order_desc": true}, "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: 48d13779-243d-4798-b625-6d8d2034cb24
version: 1.0.0
dataset_uuid: 60cb74d6-27ae-4e59-94dc-0ad5bec9bf9e
tags: []
