slice_name: Transaction events (drill by ref)
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 58__table
  viz_type: table
  query_mode: raw
  all_columns:
  - event_time
  - business_ref
  - interchange_id
  - partner
  - doc_type
  - stage
  - status
  - reason_category
  order_by_cols:
  - '["event_time", false]'
  row_limit: 500
  server_page_length: 25
  time_range: Last 30 days
query_context: '{"datasource": {"id": 58, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": ""}, "applied_time_extras": {},
  "annotation_layers": [], "url_params": {}, "custom_params": {}, "custom_form_data":
  {}, "row_limit": 500, "orderby": [["event_time", false]], "columns": ["event_time",
  "business_ref", "interchange_id", "partner", "doc_type", "stage", "status", "reason_category"],
  "metrics": []}], "form_data": {"datasource": "58__table", "viz_type": "table", "query_mode":
  "raw", "all_columns": ["event_time", "business_ref", "interchange_id", "partner",
  "doc_type", "stage", "status", "reason_category"], "order_by_cols": ["[\"event_time\",
  false]"], "row_limit": 500, "server_page_length": 25, "time_range": "Last 30 days"},
  "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: 48307a8a-e6f0-4292-8cff-a70ebfb61ed1
version: 1.0.0
dataset_uuid: d169eae4-bc06-4a4f-8785-aec0db33f8e3
tags: []
