-- ============================================================================
-- DEMO SEED — STATIC OPERATIONAL SIGNALS  (run AFTER 00_schema.sql)
--
-- This seeds ONLY the small, hand-curated tables that have no live writer in
-- the demo: the operational monitor signals (ops_*), a handful of file-grain
-- edge cases (txn_files), and the partner penalty reference. Each row encodes a
-- specific cockpit story (an endpoint down, a feed missing, a pipeline hung, a
-- monitor gone stale, a file that lost transactions inside it).
--
-- The BULK transaction world (public.txn_events + txn_rollup_hourly) is NOT
-- seeded here — that is generated by scripts/gen_shipment_world.py, which owns
-- the order world (204/990/214/210), reconciliation, and the rollup rebuild.
-- Keeping the two apart means a reseed of the transaction world never disturbs
-- these static signals, and vice-versa.
--
-- Time-sensitive columns below are re-stamped to "now" by refresh_demo_ops()
-- (sql/03_refresh_ops.sql) so the edge cases stay crisp regardless of when you
-- demo. Idempotent: truncates and re-inserts the tables it owns.
-- ============================================================================

-- 0. clean (idempotent for re-runs) — only the tables this file owns
TRUNCATE txn_files, ops_endpoint_health, ops_expected_feeds,
         ops_monitor_heartbeat, ops_pipeline_health, ref_partner_penalty
  RESTART IDENTITY;

-- ============================================================================
-- 1. FILE EDGE CASES (txn_files parent grain) — incoming & outgoing
--    Powers the File explorer + reconciliation story. The bulk per-event world
--    lives in txn_events (gen_shipment_world.py); these are the curated files.
-- ============================================================================
INSERT INTO txn_files (interchange_id, file_name, environment, partner, channel, protocol, direction,
  received_at, completed_at, status, reason_category, declared_txn_count, isa_control, gs_control, kchar) VALUES
 -- (a) declares 200 children, far fewer actually arrive -> lost INSIDE the file
 ('ICID-KROGER-0815','KROGER_204_0815.edi','prod','Kroger','sftp','edi','in',
   now()-interval '40 min', now()-interval '38 min','parsed',NULL,200,'000012845','004521',62),
 -- (b) rejected at receipt, BEFORE parse (malformed) -> visible with no children
 ('ICID-AFNEWCO-1','AFNEWCO_INV.csv','prod','AF Newco','sftp','edi','in',
   now()-interval '44 min', now()-interval '44 min','rejected','bad_input_file',NULL,NULL,NULL,180),
 -- (c) clean outgoing
 ('ICID-MAERSK-856','MAERSK_856_OUT.x12','prod','Maersk','as2','edi','out',
   now()-interval '46 min', now()-interval '45 min','delivered',NULL,48,'000099120','007781',24),
 ('ICID-WERNER-990','WERNER_990_OUT.edi','prod','Werner','sftp','edi','out',
   now()-interval '48 min', now()-interval '47 min','delivered',NULL,12,'000077431','003310',8);

-- ============================================================================
-- 2. OPERATIONAL TABLES (Q1) — the active-sweep signals (re-stamped by sql/03)
-- ============================================================================
INSERT INTO ops_endpoint_health (channel, endpoint, partner, environment, status, last_ok_at, cert_expires_at) VALUES
 ('sftp','crocs-edi','Crocs','prod','down',      now()-interval '22 min', (now()+interval '5 day')::date),   -- down + cert 5d
 ('api','rxo-track','RXO','prod','degraded',     now()-interval '2 min',  (now()+interval '3 day')::date),   -- 401s + token 3d
 ('as2','maersk-as2','Maersk','prod','up',       now()-interval '20 sec', (now()+interval '11 day')::date),
 ('sftp','target-sftp','Target','prod','up',     now()-interval '15 sec', (now()+interval '120 day')::date),
 ('sftp','crocs-edi-uat','Crocs','uat','up',     now()-interval '30 sec', (now()+interval '90 day')::date);

INSERT INTO ops_expected_feeds (partner, doc_type, channel, environment, expected_next_at, grace_minutes, last_seen_at) VALUES
 ('Werner','204','sftp','prod', now()-interval '35 min', 15, now()-interval '95 min'),  -- MISSING
 ('Kroger','856','sftp','prod', now()-interval '2 hour', 30, now()-interval '26 hour'), -- MISSING
 ('Maersk','214','sftp','prod', now()+interval '40 min', 30, now()-interval '20 min');  -- healthy

INSERT INTO ops_monitor_heartbeat (monitor_name, channel, environment, last_run_at, expected_interval_sec) VALUES
 ('van-liveness','van','prod', now()-interval '18 min', 300),   -- STALE -> sweep-integrity catch
 ('sftp-liveness','sftp','prod', now()-interval '20 sec', 300),
 ('as2-liveness','as2','prod', now()-interval '25 sec', 300),
 ('api-liveness','api','prod', now()-interval '15 sec', 300),
 ('mq-depth','mq','prod', now()-interval '10 sec', 120);

INSERT INTO ops_pipeline_health (pipeline, environment, state, queue_depth, mq_depth, consume_rate, last_consumed_at) VALUES
 ('walgreens-tl','prod','running', 20, 20, 0,    now()-interval '40 min'),  -- HUNG (running, queue>0, rate 0)
 ('air-main','prod','running',     12, 0,  240,  now()),
 ('ocean-main','prod','running',    4, 0,  180,  now()),
 ('uat-ground','uat','running',     0, 0,  0,    now()-interval '3 hour');  -- uat idle

-- ============================================================================
-- 3. REFERENCE — partner penalty (powers value-at-risk weighting)
-- ============================================================================
INSERT INTO ref_partner_penalty(partner, doc_type, penalty_usd) VALUES
 ('Werner','204',250),('Maersk','856',400),('Kroger','856',300);

-- DONE. Static signals seeded. Run gen_shipment_world.py for the bulk txn world,
-- then refresh_demo_ops() (sql/03) to re-crisp the time-sensitive rows.
